### ISSUE TITLE
Specialization

### ISSUE THREAD

**Issue by Drup** [kit-ty-kate/ocaml-monomorphic#4]
One of the big reason to use monomorphic function is performance: the specialization primitives for equalities and comparisons are much faster than the polymorphic one.

Unfortunately, the current implementation offers very very poor specialization: Nothing in the module is specialized (it's a module alias to `Pervasive` !!). Using `Monomorphic.Float.(=)` lead to specialization in the client module *if it is inlined*, but otherwise not. When using `Monomorphic.Make` on primitive types, nothing is specialized at all (even under flambda -O3).

The technique used in the implementation, while cute and short, is completely inappropriate to convey specialization information to the compiler, it needs quite a bit more info than that.

**Comment by Drup** [comment]
After several tests

```ocaml
module[@inline] Make (A : sig type t end) : sig
val (=) : A.t -> A.t -> bool
end = struct
let (=) (x : A.t) y = (=)  x y
end

module F = Make(Float)
let equal1 (a : float) b = F.(=) a b (* NOT SPECIALIZED *)
let equal2 (a : float) b = (=) a b (* SPECIALIZED *)
```

Making the compiler specialize `equal1` is more or less impossible, except by putting `
external ( = ) : A.t -> A.t -> bool = "%equal"` *in the signature*. If you want to experiment, I suggest playing with https://ocaml.godbolt.org/beta/z/E2lOKb

The compiler is being particularly bad at this :/

**Comment by Drup** [comment]
The bug was reported upstream here: https://caml.inria.fr/mantis/view.php?id=7907

**Comment by kit-ty-kate** [comment]
oops, #5 only partially fixes this issue. I'll keep it open for now.

**Comment by kit-ty-kate** [comment]
Fixed by https://github.com/kit-ty-kate/ocaml-monomorphic/commit/a375902cdfef42e38e5154ae007b4e6c5c2fa584
I've also added some test in https://github.com/kit-ty-kate/ocaml-monomorphic/commit/d0c1aa286f60db527ad0318d5ac226de5f825acb. If you have any idea how to ensure they are in sync with the stdlib (see https://github.com/kit-ty-kate/ocaml-monomorphic/commit/fdacf27eb789eacbeb9731ae8525e03fa67f2365) though, I would gladly include that.
